---
name: Publish Release

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag_name:
        description: Tag name that the major tag will point to
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}

jobs:
  gh-release:
    name: Publish Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 🥇 Update release to the latest
        id: gh-release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          token: ${{ github.token }}

      - name: 🥇 Update the major tag to include the ${{ env.TAG_NAME }} changes
        id: major-tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_NAME }}
          token: ${{ github.token }}
